multiple instances: false
relaunch in background: false
application data folder: MyApp/1.0
preferences:
  macos:
    filename: com.my-company.myapp_osx
  windows:
    filename: MyApp/1.0/MyApp Preferences.dat
file extensions:
  Text File: txt
file extension groups:
  Text Files:
    1:
      name: All Supported Files
      extensions: txt
components:
  1:
    name: MyApp
    filename: myapp/myapp.livecode
